name: Frontend
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    steps:
      - uses: actions/checkout@v3
      - name: Ssh into server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USER_NAME }}
          port: 22
          script: |
            cd /var/www/frontend/
            git pull origin main
            export PATH=$PATH:/root/.nvm/versions/node/v18.16.0/bin
            pm2 restart frontend
  send_notification_to_slack:
    name: Send notification to Slack
    runs-on: ubuntu-22.04
    if: always()
    needs: [job_a, job_b]
    steps:
      - run: |
          successText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* completed successfully."
          failureText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* failed."
          cancelledText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* was cancelled.😥"
          status="${{ (contains(needs.*.result, 'cancelled') && 'cancelled') || (contains(needs.*.result, 'failure') && 'failure') || 'success' }}"
          
          if [ "$status" = 'success' ]; then
           color='good'
           text=$successText
          elif [ "$status" = 'failure' ]; then
           color='danger'
           text=$failureText
          elif [ "$status" = "cancelled" ]; then
            color='warning'
            text=$cancelledText
          fi
          
          echo "{attachments: [{text: \"$text\", color: \"$color\"}]}" | curl \
            "${{ secrets.SLACK_WEBHOOK_URL }}" \
            -X "POST" \
            --header "Content-Type: application/json" \
            --data-binary @-
