name: Frontend

on:
  push:
    branches: [ "dev-ops" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
            node-version: 18
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.USER_NAME }}
          port: 22
          script: |
            cd /var/www/frontend/
            node -v